name: Tenex
description: Indexer for Tenex on BSC
unordered_multichain_mode: false
event_decoder: hypersync-client
# Global contracts configuration that will be shared across all chains that are defined later in the config file
# (i.e. Tenex on BSC testnet)
contracts:
  - name: PoolFactory
    handler: src/EventHandlers.ts
    events:
      - event: PoolCreated(address indexed token0, address indexed token1, bool indexed stable, address pool, uint256 unnamed)
  - name: Pool
    handler: src/EventHandlers.ts
    events:
      - event: Fees(address indexed sender, uint256 amount0, uint256 amount1)
      - event: Swap(address indexed sender, address indexed to, uint256 amount0In, uint256 amount1In, uint256 amount0Out, uint256 amount1Out)
      - event: Sync(uint256 reserve0, uint256 reserve1)
  - name: Voter
    handler: src/EventHandlers.ts
    events:
      - event: DistributeReward(address indexed sender, address indexed gauge, uint256 amount)
      - event: GaugeCreated(address indexed poolFactory, address indexed votingRewardsFactory, address indexed gaugeFactory, address pool, address bribeVotingReward, address feeVotingReward, address gauge, address creator)
  - name: VotingReward
    handler: src/EventHandlers.ts
    events:
      # - event: Deposit(address indexed from, uint256 indexed tokenId, uint256 amount)
      - event: NotifyReward(address indexed from, address indexed reward, uint256 indexed epoch, uint256 amount)
      # - event: Withdraw(address indexed from, uint256 indexed tokenId, uint256 amount)
  - name: Gauge
    handler: src/EventHandlers.ts
    events:
      - event: NotifyReward(address indexed from, uint256 amount)
  - name: PriceFetcher
    handler: src/EventHandlers.ts
    events:
      - event: PriceFetched(address indexed token, uint256 price)
        
# Used to define the different chains that contracts (defined above) will be indexed from
rollback_on_reorg: false
networks:
  - id: 56 # BSC  chainid  for TENEX
    start_block: 0
   
    # Specification of addresses per contract type defined above
    contracts:
      - name: PoolFactory
        address:
          - 0x9eFFb01a763f1ED690273167d045C69c4df2F0C3
      - name: Pool
        address:
          - 0x3a497D73A272382AE445A0628A2C41c3B0889EB3
          - 0xe8dC96b7980A1243F25468a513801241CA1CdC72
          
      - name: Voter
        address:
          - 0x866439457B98dEB907fA038728E36dB7aefEE794
      - name: VotingReward
        address:
          - 0x9FC1091Bf704F2a74399E2ae98517202cab821b6 # need to change
      - name: PriceFetcher
        address:
          - 0x5f08F9A37F3c3DD6596b81e58C635597c61Be5DE
