name: Tenex
description: Indexer for Tenex on Blast
unordered_multichain_mode: false
event_decoder: hypersync-client
# Global contracts configuration that will be shared across all chains that are defined later in the config file
# (i.e. Tenex on Blast sepolia)
contracts:
  - name: PoolFactory
    handler: src/EventHandlers.ts
    events:
      - event: PoolCreated(address indexed token0, address indexed token1, bool indexed stable, address pool, uint256 unnamed)
  - name: Pool
    handler: src/EventHandlers.ts
    events:
      - event: Fees(address indexed sender, uint256 amount0, uint256 amount1)
      - event: Swap(address indexed sender, address indexed to, uint256 amount0In, uint256 amount1In, uint256 amount0Out, uint256 amount1Out)
      - event: Sync(uint256 reserve0, uint256 reserve1)
  - name: Voter
    handler: src/EventHandlers.ts
    events:
      - event: DistributeReward(address indexed sender, address indexed gauge, uint256 amount)
      - event: GaugeCreated(address indexed poolFactory, address indexed votingRewardsFactory, address indexed gaugeFactory, address pool, address bribeVotingReward, address feeVotingReward, address gauge, address creator)
  - name: VotingReward
    handler: src/EventHandlers.ts
    events:
      # - event: Deposit(address indexed from, uint256 indexed tokenId, uint256 amount)
      - event: NotifyReward(address indexed from, address indexed reward, uint256 indexed epoch, uint256 amount)
      # - event: Withdraw(address indexed from, uint256 indexed tokenId, uint256 amount)
  - name: Gauge
    handler: src/EventHandlers.ts
    events:
      - event: NotifyReward(address indexed from, uint256 amount)
  - name: PriceFetcher
    handler: src/EventHandlers.ts
    events:
      - event: PriceFetched(address indexed token, uint256 price)
        
# Used to define the different chains that contracts (defined above) will be indexed from
rollback_on_reorg: false
networks:
  - id: 81457 # Blast  chainid  for TENEX
    start_block: 0
    # Specification of addresses per contract type defined above
    contracts:
      - name: PoolFactory
        address:
          - 0x9FC1091Bf704F2a74399E2ae98517202cab821b6
      - name: Pool
        address:
          - 0x794af1d173807dAb1aC6e1c46EA6927A361209Bf
          - 0x1D95F3f2Efb0a56Cd35e315bb74BD4AeEf2198A1
         
         
      - name: Voter
        address:
          - 0xDaE876Af086d7E2ee2CF5434faAB6DD54732BcA5
      - name: VotingReward
        address:
          - 0x83CCe00595b74D47Eb4872da4Eae36AaD1E557C2 # need to change
      - name: PriceFetcher
        address:
           - 0x053ebbdA0FDF36623ac40C5136df3789883b0493
