name: Tenex
description: Indexer for Tenex on BSC
unordered_multichain_mode: false
event_decoder: hypersync-client
# Global contracts configuration that will be shared across all chains that are defined later in the config file
# (i.e. Tenex on BSC testnet)
contracts:
  - name: PoolFactory
    handler: src/EventHandlers.ts
    events:
      - event: PoolCreated(address indexed token0, address indexed token1, bool indexed stable, address pool, uint256 unnamed)
  - name: Pool
    handler: src/EventHandlers.ts
    events:
      - event: Fees(address indexed sender, uint256 amount0, uint256 amount1)
      - event: Swap(address indexed sender, address indexed to, uint256 amount0In, uint256 amount1In, uint256 amount0Out, uint256 amount1Out)
      - event: Sync(uint256 reserve0, uint256 reserve1)
  - name: Voter
    handler: src/EventHandlers.ts
    events:
      - event: DistributeReward(address indexed sender, address indexed gauge, uint256 amount)
      - event: GaugeCreated(address indexed poolFactory, address indexed votingRewardsFactory, address indexed gaugeFactory, address pool, address bribeVotingReward, address feeVotingReward, address gauge, address creator)
  - name: VotingReward
    handler: src/EventHandlers.ts
    events:
      # - event: Deposit(address indexed from, uint256 indexed tokenId, uint256 amount)
      - event: NotifyReward(address indexed from, address indexed reward, uint256 indexed epoch, uint256 amount)
      # - event: Withdraw(address indexed from, uint256 indexed tokenId, uint256 amount)
  - name: Gauge
    handler: src/EventHandlers.ts
    events:
      - event: NotifyReward(address indexed from, uint256 amount)
  - name: PriceFetcher
    handler: src/EventHandlers.ts
    events:
      - event: PriceFetched(address indexed token, uint256 price)
        
# Used to define the different chains that contracts (defined above) will be indexed from
rollback_on_reorg: false
networks:
  - id: 97 # BSC  chainid  for TENEX
    start_block: 0
   
    # Specification of addresses per contract type defined above
    contracts:
      - name: PoolFactory
        address:
          - 0xE8f79323A023123A0AfB8Ac3F4f48d29e2AC6083
      - name: Pool
        address:
          - 0xB721107F2BCEfa5301017809d64EeB92316922fE
          - 0x34a5525920ba3936c9e3cd79262A7a54A2EE413b
         
         
      - name: Voter
        address:
          - 0x5CB8429791781de84a99d1f213588F5B299Dcd19
      - name: VotingReward
        address:
          - 0x19d372D7977A314A85EF50F4e8D0a83d06CC3fA8 # need to change
      - name: PriceFetcher
        address:
           - 0x66F296709989e47D0d5666B5cffb1201132e216a
